workflows:
  ios-please-work:
    name: Put it on iOS NOW!!!

    integrations:
      app_store_connect: Codemagic API

    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.aajintech.calculator

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build IPA for App Store
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
