workflows:
  ios:
    environment:
      xcode: latest

    scripts:
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/Runner.xcworkspace" \
            --scheme "Runner"

    artifacts:
      - build/ios/ipa/*.ipa
