workflows:
  please-work:
    name: Push to iOS!

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get flutter packages, please.
        script: flutter packages pub get
      - name: Build iOS, pretty please.
        script: flutter build ios
